version: '3.9'
services:
    db:
      image: mysql:latest
      volumes: 
        - type: bind
        - db_data:/var/lib/mysql
      ports: 
        - "3306:3306"
      networks:
        - wpnet
      restart: unless-stopped
      environment:
        MYSQL_USER:
        MYSQL_ROOT_PASSWORD:
        MYSQL_PASSWORD:
        MYSQL_DATABASE:
    wordpress:
      depends_on:
         - db
      image: wordpress:latest
      volumes:
         - .:/var/www/html/wp-content
      ports:
         - "8004:80"
      networks:
        - wpnet
      restart: unless_stopped
      environment:
        WORDPRESS_DB_USER:
        WORDPRESS_DB_HOST:
        WORDPRESS_DB_PASSWORD:
        WORDPRESS_DB_NAME:
    php:
      image: wordpressdevelop/php
      networks: 
        - wpnet
      volumes: 
    web:
      image: apache

    redis:
      image: redis
      
       
      
